name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get email
        run: echo GITHUB_EMAIL=$(git --no-pager show -s --format=\'%ae\') >> $GITHUB_ENV

      - name: Setup GIT
        run: |
          echo "Setting email to: ${GITHUB_EMAIL}"
          echo "Setting user to: ${GITHUB_ACTOR}"
          git config user.email "$GITHUB_EMAIL"
          git config user.name "$GITHUB_ACTOR"

      - name: npm intsall
        run: npm ci

      - name: Build
        run: npm run build:pages

      - name: Deploy
        run: |
          git add -A
          git commit -m "add build files"
          git push origin master

      - name: Version bump
        run: |
          npm version patch -m "ci: version bump to v%s"
          git push origin master
