name: Version

on: pull_request

jobs:
  echo:
    name: Get
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'get version'
        run: |
          echo APP_VERSION=$(git log -1 --pretty=%B)

      - name: 'echo version'
        run: |
          echo "the version is: ${APP_VERSION}"

      - name: 'echo version2'
        run: |
          echo "the version is: ${APP_VERSION2}"
