name: Version

on: pull_request

jobs:
  echo:
    name: Get
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "::set-output name=VERSION::(cat package.json | jq -r '.version')"
        id: npm

      - name: "echo version"
        run: echo "The version is ${{ steps.npm.VERSION }}"
#        env:
#          VERSION: ${{ npm version | grep 'csv' | awk -F\' '{print $4}' }}
